### ISSUE TITLE
[Feature request] Another JSON-B, JAXB implementations

### ISSUE THREAD

**Issue by rfelcman** [brunopenha/homework#2]
This is just feature request. I could be nice to make this application more flexible to use there another JSON-B, JAXB implementations like EclipseLink MOXy or Yasson.

**Comment by brunopenha** [comment]
I've add the Eclipse Yasson in this project and release a new version with it (0.0.2). 

But the implementation of JAXB from net.java it seems more simple to apply than EclipseLink MOXy. I will keep seeking another way to apply this implementation in a way that not impact too much what was already done.

But, if this change meet your expectation, you may close this issue. : )

**Comment by rfelcman** [comment]
I think, that this change is OK.
